modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="paintable_blocks"
version="1.0.0"
displayName="Paintable Blocks"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Wenbebis"
description="Adds a Paint Roller and double-sided paintable blocks."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.paintable_blocks]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.paintable_blocks]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"





# Start of user code block custom mixins
# End of user code block custom mixins


# Start of user code block dependencies configuration
# End of user code block dependencies configuration